### ISSUE TITLE
Image Factory MVP

### ISSUE THREAD

**Issue by smira** [siderolabs/image-factory#1]
```[tasklist]
### Development
- [ ] https://github.com/siderolabs/image-service/issues/2
- [ ] https://github.com/siderolabs/image-service/issues/3
- [ ] https://github.com/siderolabs/image-service/issues/5
- [ ] https://github.com/siderolabs/image-service/issues/6
- [ ] https://github.com/siderolabs/image-service/issues/7
- [ ] https://github.com/siderolabs/image-service/issues/11
- [ ] https://github.com/siderolabs/image-service/issues/12
- [ ] https://github.com/siderolabs/image-service/issues/13
- [ ] https://github.com/siderolabs/image-service/issues/18
- [ ] https://github.com/siderolabs/image-factory/issues/29
- [ ] https://github.com/siderolabs/image-service/issues/14
- [ ] https://github.com/siderolabs/image-factory/issues/38
- [ ] https://github.com/siderolabs/image-factory/issues/39
- [ ] https://github.com/siderolabs/image-service/issues/4
- [ ] https://github.com/siderolabs/image-factory/issues/43
- [ ] https://github.com/siderolabs/operations/issues/541
- [ ] https://github.com/siderolabs/talos/issues/7920
- [ ] https://github.com/siderolabs/image-factory/issues/44
- [ ] https://github.com/siderolabs/image-service/issues/19
- [ ] https://github.com/siderolabs/image-service/issues/21
- [ ] https://github.com/siderolabs/image-factory/issues/65
- [x] Ingress for `pxe.talos.dev`
- [ ] https://github.com/siderolabs/image-factory/issues/75
- [ ] https://github.com/siderolabs/image-service/issues/20
- [ ] https://github.com/siderolabs/image-factory/issues/77
```

```[tasklist]
### Deployment
- [ ] Add a draft title or issue reference here
```
